name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - dev
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install npm dependencies
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build your web application
        run: npm run build

      - name: Deploy to Firebase Hosting
        run: |
          # Determine the Firebase Hosting Chanel based on the branch name
          if [ "${{ github.ref}}" = "refs/heads/main" ]; then
            CHANNEL="main"
          elif [ "${{ github.ref}}" = "refs/heads/dev" ]; then
            CHANNEL="dev"
          elif [ "${{ github.ref}}" = "refs/heads/staging" ]; then
            CHANNEL="staging"
          else
            #If the brunch is not master, dev or staging, exit without deploying echo "Branch not set up for deployment."
          fi

           # Deploy your application to specified Hosting Chanel
          firebase hosting:channel:deploy "$CHANNEL" --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
